<?php 

/**
 * Joomla! 1.5 component summer_reader
 * Code generated by : Danny's Joomla! 1.5 MVC Component Code Generator
 * http://www.joomlafreak.be
 * date generated:  
 * @version 0.8
 * @author Danny Buytaert 
 * @package com_summer_reader
 * @license http://opensource.org/licenses/gpl-license.php GNU Public License
 **/

// no direct access
defined( '_JEXEC' ) or die( 'Restricted access' );


  
// uncomment to add custom css file for this view,
// save the css file to media/com_summer_reader/css/yourcss.css
//use media/com_summer_reader folder to store your css,js,images,...

	//$document =& JFactory::getDocument();
    //$document->addStyleSheet($this->baseurl.'/media/com_summer_reader/css/yourcss.css');

  ?>
<?php if ( $this->params->def( 'show_page_title', 1 ) ) : ?>
<h1 class="componentheading<?php echo $this->params->get( 'pageclass_sfx' ); ?>">
<?php echo $this->escape($this->params->get('page_title')); ?>
</h1>
<?php endif; ?>

<?php if( $this->params->get('show_testfield1') && $this->item->testfield1 ):?>
	<h3>Testfield1</h3>
	<?php echo $this->item->testfield1; ?>
<?php endif; ?>


<?php if( $this->params->get('show_testfield2') && $this->item->testfield2 ):?>
	<h3>Testfield2</h3>
	<?php echo $this->item->testfield2; ?>
<?php endif; ?>

<?php if (($this->params->get('show_author'))) : ?>
		<p class="small">
			<?php echo JText::_( 'Written by' ); ?>:<?php echo $this->item->created_by_alias; ?>
		</p>
<?php endif; ?>
		
<?php if ($this->params->get('show_create_date')) : ?>
		<p class="small">
		<?php echo JHTML::_('date', $this->item->created, JText::_('DATE_FORMAT_LC2')) ?>
		</p>
<?php endif; ?>

<?php if ( intval($this->item->modified) !=0 && $this->params->get('show_modify_date')) : ?>
	<p class="small">
	<?php echo JText::sprintf('LAST_UPDATED2', JHTML::_('date', $this->item->modified, JText::_('DATE_FORMAT_LC2'))); ?>
	</p>
<?php endif; ?>
		
<?php if ($this->params->get('show_hits')) : ?>
	<p class="small">
	<?php echo JText::_( 'Hits' ); ?>:<?php echo $this->item->hits; ?>
	</p>
<?php endif; ?>
